import { FormEvent, useEffect, useState } from 'react'
import { simDemo, type SimSession } from '../lib/simDemo'
import { midTruncate } from '../components/Primitives'

const INITIAL = { recipient: 'Amina Bello', corridor: 'USD → NGN', amount: '1250', memo: 'Creator payout · July' }

export function JudgeWorkspace() {
  const [workspace, setWorkspace] = useState<SimSession | null>(null)
  const [form, setForm] = useState(INITIAL)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function create() {
    setBusy(true); setError(null)
    try { setWorkspace(await simDemo.create()) } catch (e) { setError((e as Error).message) } finally { setBusy(false) }
  }
  useEffect(() => { void create() }, [])

  async function submit(event: FormEvent) {
    event.preventDefault()
    if (!workspace) return
    const amount = Number(form.amount)
    if (!Number.isFinite(amount) || amount <= 0) { setError('Enter a payout amount greater than zero.'); return }
    setBusy(true); setError(null)
    try { setWorkspace(await simDemo.payout(workspace.id, { ...form, amount })) } catch (e) { setError((e as Error).message) } finally { setBusy(false) }
  }
  async function decide(id: string, action: 'settle' | 'hold') {
    if (!workspace) return
    setBusy(true); setError(null)
    try { setWorkspace(await simDemo.decide(workspace.id, id, action)) } catch (e) { setError((e as Error).message) } finally { setBusy(false) }
  }

  const settled = workspace?.payouts.filter((p) => p.status === 'settled').length ?? 0
  const held = workspace?.payouts.filter((p) => p.status === 'held').length ?? 0

  return (
    <section className="judge-workspace">
      <div className="judge-hero">
        <div><p className="eyebrow">Interactive hackathon demo</p><h2>Make a decision.<br />Inspect the proof.</h2><p>Submit a payout, settle or hold it, then see the append-only evidence generated for this judge session.</p></div>
        <div className="judge-guardrail"><span>Sandboxed</span><b>No funds move</b><small>Session evidence is isolated and expires with the server.</small></div>
      </div>
      {error && <div className="judge-error" role="alert">{error}</div>}
      <div className="judge-grid">
        <form className="judge-form" onSubmit={submit}>
          <div className="section-kicker">1 / Create a payout</div>
          <h3>Start a fresh decision</h3>
          <label>Recipient<input value={form.recipient} onChange={(e) => setForm({ ...form, recipient: e.target.value })} minLength={2} required /></label>
          <div className="form-pair"><label>Corridor<input value={form.corridor} onChange={(e) => setForm({ ...form, corridor: e.target.value })} required /></label><label>Amount (USD)<input inputMode="decimal" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} required /></label></div>
          <label>Purpose<input value={form.memo} onChange={(e) => setForm({ ...form, memo: e.target.value })} required /></label>
          <button className="primary-action" disabled={busy || !workspace}>{busy ? 'Recording…' : 'Add to decision queue'}</button>
          <p className="form-note">Creates a fresh hash-chained record. This is not a live payment instruction.</p>
        </form>

        <div className="judge-queue">
          <div className="queue-heading"><div><div className="section-kicker">2 / Decide</div><h3>Decision queue</h3></div><button className="reset-workspace" onClick={() => void create()} disabled={busy}>New workspace</button></div>
          {!workspace && <div className="judge-skeleton" />}
          {workspace?.payouts.length === 0 && <div className="judge-empty"><strong>Your queue is ready.</strong><span>Add a payout to demonstrate the approval trail.</span></div>}
          {workspace?.payouts.map((payout) => <article className="judge-payout" key={payout.id}>
            <div className="payout-title"><div><strong>{payout.recipient}</strong><span>{payout.corridor} · {payout.memo}</span></div><b>${payout.amount.toLocaleString()}</b></div>
            <div className="payout-footer"><span className={`risk risk-${payout.risk}`}>{payout.risk} review</span>{payout.status === 'pending' ? <div className="decision-actions"><button onClick={() => void decide(payout.id, 'hold')} disabled={busy}>Hold</button><button className="settle" onClick={() => void decide(payout.id, 'settle')} disabled={busy}>Settle demo</button></div> : <span className={`demo-status ${payout.status}`}>{payout.status === 'settled' ? 'Settled · simulated' : 'Held for review'}</span>}</div>
          </article>)}
        </div>
      </div>

      <div className="judge-proof">
        <div className="proof-summary"><div className="section-kicker">3 / Verify</div><h3>Proof generated by your actions</h3><p>{workspace?.notice ?? 'Creating isolated workspace…'}</p><div className="proof-stats"><span><b>{workspace?.events.length ?? 0}</b> events</span><span><b>{settled}</b> simulated settlements</span><span><b>{held}</b> holds</span></div></div>
        <div className="proof-chain">
          <div className="chain-state"><span className={workspace?.chain.verified ? 'ok' : ''} />{workspace?.chain.verified ? 'Chain verified' : 'Verifying chain'}</div>
          {workspace?.events.slice(-5).reverse().map((event) => <div className="proof-event" key={event.id}><div><b>{event.type.replace('.', ' · ')}</b><span>{event.actor} · {event.subject}</span></div><code>{midTruncate(event.event_hash, 6, 6)}</code></div>)}
        </div>
      </div>
    </section>
  )
}
